import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//imgs
import field from "../assets/field_bg.png"
import skybox from "../assets/skybox.png"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
        <Image 
            src={skybox}
            layout='fill'
            objectFit='cover'
            className={styles.background}
            priority
          />
          <Image 
            src={field}
            layout='fill'
            objectFit='cover'
            className={styles.foreground}
            priority
          />
        </div>
        <div className={styles.bg}>
          <div className={styles.one}></div>
          <div className={styles.two}></div>
          <div className={styles.three}></div>
          <div className={styles.four}></div>
          <div className={styles.five}></div>
        </div>
      </main>
      <img src={field} alt="" />
    </div>
  )
}
